### ISSUE TITLE
Needs update for new variant

### ISSUE THREAD

**Issue by ManuWar73** [Pustur/fall-guys-perfect-match#1]
We need the new perfect match variant

**Comment by Pustur** [comment]
Hi @ManuWar73 and thanks for the report.

I don't play anymore but it seems like the new icons are these ones?

<img width="1195" alt="Screenshot 2022-10-18 at 00 34 28" src="https://user-images.githubusercontent.com/13663338/196297250-3f931bc7-db5b-481e-b601-060f5dcd7115.png">

Is it still possible to get the fruits version?

Thanks

**Comment by Pustur** [comment]
Released version with new icons
