### ISSUE TITLE
Trace new SVG icons from PNG image

### ISSUE THREAD

**Issue by Pustur** [Pustur/fall-guys-perfect-match#2]
## Instructions

I need someone with experience in tracing SVG from this image:

<img width="1195" alt="Screenshot 2022-10-18 at 00 34 28" src="https://user-images.githubusercontent.com/13663338/196297250-3f931bc7-db5b-481e-b601-060f5dcd7115.png">

## Notes

- I need all 6 icons but this issue can be split between different people if needed.
- The icons don't need to be extremely detailed as they will usually be rendered at like ~200px
- Please also read the clarification I made in [this comment](https://github.com/Pustur/fall-guys-perfect-match/issues/2#issuecomment-1288094956)

## Previous work

Examples of previous SVGs:

<ul>
<li><a href="https://github.com/Pustur/fall-guys-perfect-match/blob/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/bananas.svg"><img width="100" alt="bananas" src="https://raw.githubusercontent.com/Pustur/fall-guys-perfect-match/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/bananas.svg"></a></li>
<li><a href="https://github.com/Pustur/fall-guys-perfect-match/blob/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/cherries.svg"><img width="100" alt="cherries" src="https://raw.githubusercontent.com/Pustur/fall-guys-perfect-match/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/cherries.svg"></a></li>
<li><a href="https://github.com/Pustur/fall-guys-perfect-match/blob/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/grapes.svg"><img width="100" alt="grapes" src="https://raw.githubusercontent.com/Pustur/fall-guys-perfect-match/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/grapes.svg"></a></li>
<li><a href="https://github.com/Pustur/fall-guys-perfect-match/blob/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/mango.svg"><img width="100" alt="mango" src="https://raw.githubusercontent.com/Pustur/fall-guys-perfect-match/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/mango.svg"></a></li>
<li><a href="https://github.com/Pustur/fall-guys-perfect-match/blob/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/orange.svg"><img width="100" alt="orange" src="https://raw.githubusercontent.com/Pustur/fall-guys-perfect-match/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/orange.svg"></a></li>
<li><a href="https://github.com/Pustur/fall-guys-perfect-match/blob/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/watermelon.svg"><img width="100" alt="watermelon" src="https://raw.githubusercontent.com/Pustur/fall-guys-perfect-match/c76a252ca99ffef50d14c22d7c2c8a7ed33e73f4/img/watermelon.svg"></a></li>
</ul>

## Linked issues

Related to: #1

**Comment by mvisic** [comment]
![boot](https://user-images.githubusercontent.com/22491113/197188740-609e9843-1397-4d31-aa1b-9df0ee83bc05.svg)

**Comment by Pustur** [comment]
Hi @mvisic, thanks for your interest.

Maybe I should have specified this in the original post, but the icons should be traced manually.

Tools that convert them automatically don't do a good enough job to be usable without manual intervention and the svg end up weighing more than if I had used a PNG in the first place.

File size is important to me, so I have to discard your attempt.

**Comment by haritmohanta** [comment]
Hi @Pustur, I am interested in this project !!!
I have some doubts. Do I have to convert png image to Svg??

**Comment by Pustur** [comment]
Hi @haritmohanta, thanks for your interest.

Yes, each icon that you see in the image needs to be converted to svg for usage in the website (https://fall-guys-perfect-match.netlify.app)

How you do it is not important, as long as the resulting file size is low (<10kb) and the image looks almost the same as the provided image.

I don't remember which software I used when tracing the fruits, but some options can be: Adobe Illustrator, Inkscape, Sketch.  
I'm sure there are even some free, browser based apps that can do it.

I hope I answered your questions, don't hesitate to ask if you have more.

PS: each icon should be in its own file.

**Comment by haritmohanta** [comment]
> Hi @haritmohanta, thanks for your interest.
> 
> Yes, each icon that you see in the image needs to be converted to svg for usage in the website (https://fall-guys-perfect-match.netlify.app)
> 
> How you do it is not important, as long as the resulting file size is low (<10kb) and the image looks almost the same as the provided image.
> 
> I don't remember which software I used when tracing the fruits, but some options can be: Adobe Illustrator, Inkscape, Sketch. I'm sure there are even some free, browser based apps that can do it.
> 
> I hope I answered your questions, don't hesitate to ask if you have more.
> 
> PS: each icon should be in its own file.

Please assign me this task.

**Comment by Pustur** [comment]
Since there seems to be some misunderstanding about what the work entails, I have provided a video that shows the general workflow that I went through when creating the fruits SVGs.

https://youtu.be/s-kPg4vYKfk?t=1283

This work takes a bit of time and patience, it's not a simple re-export of the images.

**Comment by Pustur** [comment]
Hey @haritmohanta, 

just wanted to know if you think you're going to work on the last icon or not? It's not a problem if you can't.

EDIT: I'll do the last icon, thanks @haritmohanta for the contribution!

**Comment by haritmohanta** [comment]
> Hey @haritmohanta, 
> 
> just wanted to know if you think you're going to work on the last icon or not? It's not a problem if you can't.
> 
> EDIT: I'll do the last icon, thanks @haritmohanta for the contribution!

Sorry for replying late I was having a medical issue so I couldn't reply to you that I wouldn't be able to complete last one soon
